### ISSUE TITLE
should add docs how to mange different type of data sources

### ISSUE THREAD

**Issue by hoatle** [teracyhq-incubator/teracy-dev-k8s#14]
different types of data sources:
- data store with ceph (rook operator)
- database
- block storage
- etc

how to deploy, live backup, backup verification and restore with best practices for a HA system by using helm chart; zero downtime upgrade/downgrade/backup/restore

- [ ] mysql
- [ ] postgresql
- [ ] mongodb
- [ ] minio

etc

**Comment by hoatle** [comment]
ref: https://coreos.com/blog/introducing-operators.html

**Comment by hoatle** [comment]
https://github.com/operator-framework use operator to automate it all

**Comment by hoatle** [comment]
expect: operators are used to manage all restful apps

**Comment by hoatle** [comment]
https://github.com/oracle/mysql-operator

**Comment by hoatle** [comment]
https://github.com/operator-framework/awesome-operators

**Comment by hoatle** [comment]
Rook deployment with https://rook.io/docs/rook/v0.8/helm-operator.html:

- make sure to identify the `kubelet_flexvolumes_plugins_dir`, it is `/var/lib/kubelet/volume-plugins` by default on kubespray

- Set the `agent.flexVolumeDirPath` key to the right value:

```
$ helm install --namespace rook-ceph-system rook-beta/rook-ceph --set=agent.flexVolumeDirPath=/var/lib/kubelet/volume-plugins
```

Just need to note on the `flexVolumeDirPath` to set the right value, for other things, just follow the Rook docs.

**Comment by hoatle** [comment]
after `rook-ceph-block` storageclass is available, we can use it mysql-operator cluster, for example:

```
apiVersion: mysql.oracle.com/v1alpha1
kind: Cluster
metadata:
  name: my-app-db
  namespace: test
spec:
  members: 3
  volumeClaimTemplate:
    metadata:
      name: data
    spec:
      storageClassName: rook-ceph-block
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
```
