### ISSUE TITLE
should set vm_memory and vm_cpus dynamically basing on the num_instances

### ISSUE THREAD

**Issue by hoatle** [teracyhq-incubator/teracy-dev-k8s#65]
should calculate the recommended configuration memory and cpus so that the cluster should work normally and set it dynamically if not overridden by users.

**Comment by hoatle** [comment]
related for yaml config that we can use for extensions https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/

```yaml
resources:
  - _id: "teracy-dev-k8s"
    extension_name: "teracy-dev-k8s"
    requests:
      memory: "64Mi"
      cpu: "250m"
    limits:
      memory: "128Mi"
      cpu: "500m"
```
