### ISSUE TITLE
should remove the swap provisioner to improve performance

### ISSUE THREAD

**Issue by hieptranquoc** [teracyhq-incubator/teracy-dev-k8s#67]
actual:
```
provisioners:
      - _id: "k8s-0"
        name: "teracy-dev-k8s-swapoff"
        type: shell
        enabled: true
        inline: swapoff -a
```

current: Currently kubespray uses kubeadm by default, during the process of disabling the swap disabled.
