### ISSUE TITLE
should upgrade to use the latest kubespray v2.12.1

### ISSUE THREAD

**Issue by hoatle** [teracyhq-incubator/teracy-dev-k8s#94]
https://github.com/kubernetes-sigs/kubespray/releases/tag/v2.12.1

make sure it works with existing docs

**Comment by hoatle** [comment]
my latest check:
- 1 node with ansible guest mode: works
- 1 node with ansible host mode: works
- 3 nodes with ansible guest mode: known issue, does not work yet (#20)
- 3 nodes with ansible host mode: did not work as expected
This is my config_override.yaml file:

```yaml
teracy-dev:

  entry_location:
    git:
      remote:
        origin: git@github.com:hoatle/teracy-dev-entry-k8s.git
      branch: develop
    sync: false

  extensions:

    - _id: "entry-k8s"
      path:
        lookup: workspace
      location:
          git:
            remote:
              origin: git@github.com:hoatle/teracy-dev-k8s.git
              upstream: git@github.com:teracyhq-incubator/teracy-dev-k8s.git
            branch: develop
      enabled: true


teracy-dev-certs:
  ansible:
    mode: host


teracy-dev-k8s:
  ansible:
    verbose: v
    mode: host

  num_instances: 3
  vm_memory: 1200
  vm_cpus: 1
```

the errors after `$ vagrant up`

```
TASK [etcd : Gen_certs | run cert generation script] ***************************
Thursday 20 February 2020  13:09:31 +0700 (0:00:00.081)       0:07:36.710 ***** 
fatal: [k8s-03 -> 127.0.0.1]: FAILED! => {"changed": true, "cmd": ["bash", "-x", "/usr/local/bin/etcd-scripts/make-ssl-etcd.sh", "-f", "/etc/ssl/etcd/openssl.conf", "-d", "/etc/ssl/etcd/ssl"], "delta": "0:00:00.003778", "end": "2020-02-20 06:09:30.373905", "msg": "non-zero return code", "rc": 127, "start": "2020-02-20 06:09:30.370127", "stderr": "bash: /usr/local/bin/etcd-scripts/make-ssl-etcd.sh: No such file or directory", "stderr_lines": ["bash: /usr/local/bin/etcd-scripts/make-ssl-etcd.sh: No such file or directory"], "stdout": "", "stdout_lines": []}

NO MORE HOSTS LEFT *************************************************************

PLAY RECAP *********************************************************************
k8s-01                     : ok=26   changed=7    unreachable=0    failed=1    skipped=41   rescued=0    ignored=0   
k8s-02                     : ok=24   changed=7    unreachable=0    failed=1    skipped=35   rescued=0    ignored=0   
k8s-03                     : ok=331  changed=47   unreachable=0    failed=1    skipped=277  rescued=0    ignored=0   

Thursday 20 February 2020  13:09:31 +0700 (0:00:00.174)       0:07:36.885 ***** 
=============================================================================== 
download : download_file | Download item ------------------------------- 59.70s
kubernetes/preinstall : Install packages requirements ------------------ 49.50s
download : download_container | Download image if required ------------- 45.32s
bootstrap-os : Install dbus for the hostname module -------------------- 42.98s
container-engine/docker : ensure docker packages are installed --------- 35.13s
download : download_file | Download item ------------------------------- 18.39s
download : download_container | Download image if required ------------- 16.85s
download : download_container | Download image if required ------------- 14.09s
download : download_container | Download image if required ------------- 11.88s
download : download_container | Download image if required ------------- 10.52s
container-engine/docker : ensure docker-ce repository is enabled ------- 10.51s
download : download_container | Download image if required -------------- 8.88s
download : download_container | Download image if required -------------- 8.78s
download : download_container | Download image if required -------------- 7.98s
download : download_container | Download image if required -------------- 7.41s
download : download_file | Download item -------------------------------- 7.39s
download : download_container | Download image if required -------------- 2.70s
download : download | Download files / images --------------------------- 1.68s
bootstrap-os : Fetch /etc/os-release ------------------------------------ 1.53s
container-engine/docker : ensure docker-ce repository public key is installed --- 1.42s
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

@hieptranquoc please check and fix this.
